language: python
python:
  - "3.6"

services:
  - postgresql

cache:
  pip: true

before_install:
  - cd capstone

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt

script:
  - pytest
