name: Lints

on: [push, pull_request]

defaults:
  run:
    working-directory: capstone

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Flake8
        run: |
          pip install `egrep -o 'flake8==\S+' requirements.txt`  # install our version of flake8
          flake8
